spring:
  application:
    name: t1-java-demo
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/postgres
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

management:
  metrics:
    tags:
      appName: @project.build.finalName@
      application: @project.name@
      appVersion: @project.version@
  endpoints:
    enabled-by-default: true
    web.exposure.include: health,prometheus,metrics,info,kafka
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        group:
          readiness:
            include: db
    shutdown.enabled: true
    restart.enabled: true
    prometheus.enabled: true
    logfile.enabled: true

logging:
  level:
    ROOT: DEBUG
    ru.t1.java.demo.controller.ClientController: DEBUG
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      auto-offset-reset: earliest
      max.poll.records: 10
      session-timeout: 10000
      heartbeat.interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 3
      linger.ms: 1
#      request.timeout.ms: 5000
#      delivery.timeout.ms: 60000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      client_transactions: t1_demo_client_transactions
      t1_demo_accounts: _t1_demo_accounts
      t1_demo_transactions: _t1_demo_transactions
      t1_demo_transaction_accept: _t1_demo_transaction_accept
      t1_demo_transaction_result: _t1_demo_transaction_result
      metrics: t1_demo_metrics
    listener:
      poll-timeout: 3000

track:
  errors-to-track: JsonParseException, IOException
  kafka:
    enabled: ${TRACK_KAFKA_LOG_ENABLED:true}
    bootstrap-server: localhost:9092
    data-source-error-topic: t1_demo_data_source_error
    time-limit-exceed: t1_demo_time_limit_exceed
  db:
    enabled: false
  time-limit-exceed: 1000
  log-level: DEBUG

integration:
  url: http://localhost:1398
  resource: /bsc-wire-mock/api/client/check
  retry-count: 3
  retry-backoff: 1000